<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['protocol'] = 'sendmail';
$config['mailpath'] = '/usr/sbin/sendmail';
$config['charset'] = 'iso-8859-1';
$config['wordwrap'] = TRUE;
$config['smtp_host'] = "mail.minsal.cl";
$config['smtp_user'] = "sistemas";
$config['smtp_pass'] = "siste14S";
$config['smtp_port'] = 25;
$config['charset'] = "utf-8";
